from datetime import datetime as _DateTime
from pathlib import Path
from typing import Any, Mapping, Sequence

legacy: Any

datetime: type[_DateTime]
REPO_ROOT: Path
RUNTIME_DIR: Path
STATE_PATH: Path
STOP: bool
MAX_ATTEMPTS: int
TASK_TIMEOUT_SECONDS: float
DEFAULT_HOURS: float
MIN_HOURS: float
MAX_HOURS: float
AUTOMATION_TASKS_PER_GATE: int
AUTOMATION_TASKS: tuple[str, ...]
TASK_LEDGER_PATH: Path
MAX_TASK_TEXT_CHARS: int
ENGINEERING_TASKS: tuple[str, ...]

class OvernightState:
    schema_version: int
    run_id: str
    started_at: str
    deadline_at: str
    worktree: str
    branch: str
    phase: str
    current_task: str
    requested_task: str
    task_number: int
    completed_tasks: int
    failed_tasks: int
    current_attempt: int
    automation_tasks_since_gate: int
    automation_gates: int
    provider_limit_pauses: int
    last_result: str
    next_task: str
    stop_reason: str
    recent_tasks: list[str]
    fallback_router_disabled_until: str

    def __init__(
        self,
        *,
        schema_version: int,
        run_id: str,
        started_at: str,
        deadline_at: str,
        worktree: str,
        branch: str,
        phase: str,
        current_task: str,
        requested_task: str = ...,
        task_number: int = ...,
        completed_tasks: int = ...,
        failed_tasks: int = ...,
        current_attempt: int = ...,
        automation_tasks_since_gate: int = ...,
        automation_gates: int = ...,
        provider_limit_pauses: int = ...,
        last_result: str = ...,
        next_task: str = ...,
        stop_reason: str = ...,
        recent_tasks: list[str] = ...,
        fallback_router_disabled_until: str = ...,
    ) -> None: ...

    def to_dict(self) -> dict[str, Any]: ...

def log_event(kind: str, **data: Any) -> None: ...
def now_utc() -> Any: ...
def save_state(state: OvernightState) -> None: ...
def load_state() -> OvernightState | None: ...
def acquire_lock() -> None: ...
def release_lock() -> None: ...
def validate_patch_paths(patch: str, allow_delete: bool, worktree: Path | None = ...) -> None: ...
def control_script(name: str) -> Path: ...
def command(command: list[str], cwd: Path, timeout: float) -> tuple[int, str]: ...
def healthy(url: str) -> bool: ...
def ensure_services() -> list[Any]: ...
def ensure_worktree(path: Path, branch: str, *, resume: bool) -> None: ...
def browser_observation() -> dict[str, Any] | None: ...
def runtime_watchdog_is_live(*, max_age_seconds: float = ...) -> bool: ...
def provider_condition(code: int, output: str) -> str | None: ...
def browser_auth_required() -> bool: ...
def fallback_router_available(state: OvernightState) -> bool: ...
def disable_fallback_router(state: OvernightState, reason: str) -> None: ...
def task_key(task: str) -> str: ...
def load_task_ledger() -> dict[str, dict[str, Any]]: ...
def save_task_ledger(ledger: Mapping[str, Mapping[str, Any]]) -> None: ...
def record_task_ledger(task: str, status: str, *, commit: str | None = ..., evidence: str = ..., phase: str = ..., automation_continue: bool = ...) -> None: ...
def automation_gate_is_satisfied(evidence: Mapping[str, object]) -> bool: ...
def automation_gate_evidence(state: OvernightState) -> dict[str, str]: ...
def choose_unique(candidates: Sequence[str], state: OvernightState) -> str: ...
def parse_response(response: str) -> tuple[str, str, str, str, bool, dict[str, str]]: ...
def completion_contract(status: str, values: dict[str, str]) -> bool: ...
def build_prompt(task: str, state: OvernightState, failure: str = ...) -> str: ...
def choose_next_task(state: OvernightState, suggested: str) -> str: ...
def fast_local_gate(worktree: Path) -> str: ...
def verify_and_commit(worktree: Path, branch: str, task: str, patch: str, allow_delete: bool, *, push: bool) -> tuple[str, str]: ...
def standby_until_ready(state: OvernightState, *, wait_for_auth: bool = ..., max_wait_seconds: float | None = ...) -> bool: ...
def sleep_until_retry(state: OvernightState, seconds: float) -> bool: ...
def invoke_chat(task: str, state: OvernightState, failure: str) -> tuple[int, str]: ...
def run(state: OvernightState, *, push: bool) -> None: ...
def finish_state(state: OvernightState, reason: str) -> None: ...
def main() -> int: ...
